### PR TITLE
Made self-tables be pushed on the stack for future use.

### PR DESCRIPTION
**Pull request by Belkharym**
This allows for optimizations on BittyBuzz. It could also be applied to Buzz, if it is needed.

### CODE REVIEW

**Comment by beltrame** [comment]
Looks good to me. @ilpincy ? Any final words before merge?

**Comment by AnthonyD973** [comment]
@Belkharym, @ilpincy and I were discussing about this yesterday. This would change a behavior of Buzz. Here is an example:

```
function selfx_printer() {
  print self.x
}

u = {
  .x = 67
  .fun = selfx_printer
}

u.fun() # Should this be an error? Or should it print 67?
```

This would print 67 if Buzz did the same activation record optimization we will do in BittyBuzz (which is how JavaScript behaves). Currently tough, the self table would be kept, and since the closure wasn't created inside a table, the `self` table would be `nil`, so there would be an error. This is how Python would behave.

To decide on the correct behavior @ilpincy said he was going to talk with another professor, as well as with you, about what behavior would be best.

**Comment by beltrame** [comment]
I've given some thought as well on the subject, and I think this is the correct behavior (to print 67) for free functions. Carlo told me of his tests with Python, where he used a class:

```python
class T(object):
    x = 34
    def fun(self):
         print(self.x)
 
class U(object):
     x = 21
     def __init__(self, t):
         self.fun = t.fun

U(T()).fun() # Prints 34
```
In this case the closure is a bound method to an object T, and it should print T.x. For free functions, there is no method binding, so it should use the symbols that are in its scope or above. I guess we could go the Python route, and make bound methods...

BTW, if you are curious, you can unbind methods in Python by getting the function pointer and rebinding to a new class. Try: 
```python

class T(object):
    x = 34
    def fun(self):
         print(self.x)
 
class U(object):
     x = 21
     def __init__(self, t):
         self.fun = types.MethodType(t.fun.__func__, U) 

U(T()).fun() # Prints 21
```

**Comment by ilpincy** [comment]
During our discussion yesterday at some point i proposed what Gio is saying, too. I also think it's the Python route is the best.

**Pull request merged**
